import { Player } from '../../models/Player';
import { Team } from '../../models/Team';

export const playersArr: Player[] = [
    {
        id: 1,
        nickname: 'lorem',
        name: 'ipsum',
        age: 23,
        nationality: 'Brazil',
        team: 'CSGO Team',
    },
    {
        id: 2,
        nickname: 'lorem',
        name: 'ipsum',
        age: 23,
        nationality: 'Brazil',
        team: 'CSGO Team',
    },
    {
        id: 3,
        nickname: 'lorem',
        name: 'ipsum',
        age: 23,
        nationality: 'Brazil',
        team: 'CSGO Team',
    },
    {
        id: 4,
        nickname: 'lorem',
        name: 'ipsum',
        age: 23,
        nationality: 'Brazil',
        team: 'CSGO Team',
    },
    {
        id: 5,
        nickname: 'lorem',
        name: 'ipsum',
        age: 23,
        nationality: 'Brazil',
        team: 'CSGO Team',
    },
    {
        id: 6,
        nickname: 'lorem',
        name: 'ipsum',
        age: 23,
        nationality: 'Brazil',
        team: 'CSGO Team',
    },
    {
        id: 7,
        nickname: 'lorem',
        name: 'ipsum',
        age: 23,
        nationality: 'Brazil',
        team: 'CSGO Team',
    },
    {
        id: 8,
        nickname: 'lorem',
        name: 'ipsum',
        age: 23,
        nationality: 'Brazil',
        team: 'CSGO Team',
    },
    {
        id: 9,
        nickname: 'lorem',
        name: 'ipsum',
        age: 23,
        nationality: 'Brazil',
        team: 'CSGO Team',
    },
];

export const teamsArr: Team[] = [
    {
        id: 1,
        name: 'Team 1',
        location: 'Brazil',
        region: 'North America',
        foundedYear: 2018,
        players: [
            {
                id: 1,
                nickname: 'lorem',
                name: 'ipsum',
                age: 23,
                nationality: 'Brazil',
                team: 'CSGO Team',
            },
            {
                id: 2,
                nickname: 'lorem',
                name: 'ipsum',
                age: 23,
                nationality: 'Brazil',
                team: 'CSGO Team',
            },
            {
                id: 3,
                nickname: 'lorem',
                name: 'ipsum',
                age: 23,
                nationality: 'Brazil',
                team: 'CSGO Team',
            },
        ],
    },
    {
        id: 2,
        name: 'Team 2',
        location: 'Brazil',
        region: 'Europe',
        foundedYear: 2016,
        players: [
            {
                id: 4,
                nickname: 'lorem',
                name: 'ipsum',
                age: 23,
                nationality: 'Brazil',
                team: 'CSGO Team',
            },
            {
                id: 5,
                nickname: 'lorem',
                name: 'ipsum',
                age: 23,
                nationality: 'Brazil',
                team: 'CSGO Team',
            },
            {
                id: 6,
                nickname: 'lorem',
                name: 'ipsum',
                age: 23,
                nationality: 'Brazil',
                team: 'CSGO Team',
            },
        ],
    },
    {
        id: 3,
        name: 'Team 3',
        location: 'Brazil',
        region: 'South America',
        foundedYear: 2019,
        players: [
            {
                id: 7,
                nickname: 'lorem',
                name: 'ipsum',
                age: 23,
                nationality: 'Brazil',
                team: 'CSGO Team',
            },
            {
                id: 8,
                nickname: 'lorem',
                name: 'ipsum',
                age: 23,
                nationality: 'Brazil',
                team: 'CSGO Team',
            },
            {
                id: 9,
                nickname: 'lorem',
                name: 'ipsum',
                age: 23,
                nationality: 'Brazil',
                team: 'CSGO Team',
            },
        ],
    },
];
